import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ZipBuy",
  description: "Generated by create next app",
  icons: {
    icon: "/_Orange Modern Logo-modified.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
